### ISSUE TITLE
Having Problem Training

### ISSUE THREAD

**Issue by vogler123** [AntonMu/TrainYourOwnYOLO#72]
Dear Anton,
I followed your well written tutorial and I seem to have an issue with training. When I want to start training, the following error messages appear (I'm using Python 3.7.6):

C:\yolo\2_Training>python Train_YOLO.py
Using TensorFlow backend.
2020-01-17 14:46:20.007594: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64
_100.dll not found
2020-01-17 14:46:20.014193: I tensorflow/stream_executor/cuda/cudart_stub.cc:29]
 Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING: Logging before flag parsing goes to stderr.
W0117 14:46:22.321202  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:95: The name tf.reset_default_graph is deprecated. Please use tf.compat.v
1.reset_default_graph instead.

W0117 14:46:22.321202  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:98: The name tf.placeholder_with_default is deprecated. Please use tf.com
pat.v1.placeholder_with_default instead.

W0117 14:46:22.321202  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:102: The name tf.get_default_graph is deprecated. Please use tf.compat.v1
.get_default_graph instead.

W0117 14:46:22.336827  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.place
holder instead.

W0117 14:46:22.336827  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.unif
orm instead.

W0117 14:46:22.352451  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.
v1.get_default_session instead.

W0117 14:46:22.352451  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.Confi
gProto instead.

W0117 14:46:22.352451  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:186: The name tf.Session is deprecated. Please use tf.compat.v1.Session i
nstead.

2020-01-17 14:46:22.363361: I tensorflow/core/platform/cpu_feature_guard.cc:142]
 Your CPU supports instructions that this TensorFlow binary was not compiled to
use: AVX2
2020-01-17 14:46:22.372660: I tensorflow/stream_executor/platform/default/dso_lo
ader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-01-17 14:46:22.703434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
618] Found device 0 with properties:
name: GeForce GTX 850M major: 5 minor: 0 memoryClockRate(GHz): 0.9015
pciBusID: 0000:0a:00.0
2020-01-17 14:46:22.712369: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64
_100.dll not found
2020-01-17 14:46:22.720114: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'cublas64_100.dll'; dlerror: cublas64
_100.dll not found
2020-01-17 14:46:22.730215: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'cufft64_100.dll'; dlerror: cufft64_1
00.dll not found
2020-01-17 14:46:22.740197: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'curand64_100.dll'; dlerror: curand64
_100.dll not found
2020-01-17 14:46:22.748358: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'cusolver64_100.dll'; dlerror: cusolv
er64_100.dll not found
2020-01-17 14:46:22.757595: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'cusparse64_100.dll'; dlerror: cuspar
se64_100.dll not found
2020-01-17 14:46:22.766720: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.d
ll not found
2020-01-17 14:46:22.777468: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1
641] Cannot dlopen some GPU libraries. Please make sure the missing libraries me
ntioned above are installed properly if you would like to use GPU. Follow the gu
ide at https://www.tensorflow.org/install/gpu for how to download and setup the
required libraries for your platform.
Skipping registering GPU devices...
2020-01-17 14:46:22.959342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-17 14:46:22.965080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
165]      0
2020-01-17 14:46:22.969206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
178] 0:   N
W0117 14:46:22.972037  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:190: The name tf.global_variables is deprecated. Please use tf.compat.v1.
global_variables instead.

W0117 14:46:22.972037  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:199: The name tf.is_variable_initialized is deprecated. Please use tf.com
pat.v1.is_variable_initialized instead.

W0117 14:46:22.972037  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:206: The name tf.variables_initializer is deprecated. Please use tf.compa
t.v1.variables_initializer instead.

W0117 14:46:22.987680  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat
.v1.nn.fused_batch_norm instead.

W0117 14:46:26.895240  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:2018: The name tf.image.resize_nearest_neighbor is deprecated. Please use
 tf.compat.v1.image.resize_nearest_neighbor instead.

Create YOLOv3 model with 9 anchors and 1 classes.
C:\Users\Matthias\AppData\Local\Programs\Python\Python37\lib\site-packages\keras
\engine\saving.py:1140: UserWarning: Skipping loading of weights for layer conv2
d_59 due to mismatch in shape ((1, 1, 1024, 18) vs (255, 1024, 1, 1)).
  weight_values[i].shape))
C:\Users\Matthias\AppData\Local\Programs\Python\Python37\lib\site-packages\keras
\engine\saving.py:1140: UserWarning: Skipping loading of weights for layer conv2
d_59 due to mismatch in shape ((18,) vs (255,)).
  weight_values[i].shape))
C:\Users\Matthias\AppData\Local\Programs\Python\Python37\lib\site-packages\keras
\engine\saving.py:1140: UserWarning: Skipping loading of weights for layer conv2
d_67 due to mismatch in shape ((1, 1, 512, 18) vs (255, 512, 1, 1)).
  weight_values[i].shape))
C:\Users\Matthias\AppData\Local\Programs\Python\Python37\lib\site-packages\keras
\engine\saving.py:1140: UserWarning: Skipping loading of weights for layer conv2
d_67 due to mismatch in shape ((18,) vs (255,)).
  weight_values[i].shape))
C:\Users\Matthias\AppData\Local\Programs\Python\Python37\lib\site-packages\keras
\engine\saving.py:1140: UserWarning: Skipping loading of weights for layer conv2
d_75 due to mismatch in shape ((1, 1, 256, 18) vs (255, 256, 1, 1)).
  weight_values[i].shape))
C:\Users\Matthias\AppData\Local\Programs\Python\Python37\lib\site-packages\keras
\engine\saving.py:1140: UserWarning: Skipping loading of weights for layer conv2
d_75 due to mismatch in shape ((18,) vs (255,)).
  weight_values[i].shape))
Load weights C:\yolo\2_Training\src\keras_yolo3\yolo.h5.
Freeze the first 249 layers of total 252 layers.
W0117 14:46:31.845515  6352 module_wrapper.py:139] From C:\Users\Matthias\AppDat
a\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_back
end.py:1521: The name tf.log is deprecated. Please use tf.math.log instead.

W0117 14:46:31.851520  6352 deprecation.py:323] From C:\Users\Matthias\AppData\L
ocal\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_backend
.py:3080: where (from tensorflow.python.ops.array_ops) is deprecated and will be
 removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "Train_YOLO.py", line 184, in <module>
    lines = ChangeToOtherMachine(lines, remote_machine="")
  File "C:\yolo\Utils\Train_Utils.py", line 238, in ChangeToOtherMachine
    suffix = (file.split(repo))[1]
IndexError: list index out of range

**Comment by silvestre139** [comment]
@vogler123 did you install all dependencies? and if some of the dependencies failed, try to update your pip version, and try testing the Miniman_Example file to make sure that everything is up and running before you move to the training stage.

**Comment by vogler123** [comment]
Thanks for your response,
I first tested it with the cat example and it worked very well. I could download some new cat pictures and have them classified very fast!
I redid the whole thing on my ubuntu 16.04 machine and I had the same error with the Minimal_example running very well

**Comment by silvestre139** [comment]
@vogler123 all the errors on the logs are referring to the GPU, did you installed"pip isntall tensorflow-gpu" or "conda tensorflow-pgu" already?

**Comment by AntonMu** [comment]
Hi! Glad you liked the tutorial.

It's most likely related to using a different folder name ('yolo' instead
of 'TrainYourOwnYOLO') and not using python virtual environments.

You should be able to solve this with the provided instructions.

**Comment by vogler123** [comment]
Ok!
Thanks for the hint with the folder name!
I will try that asap

**Comment by vogler123** [comment]
I got i working now!
The problem was most likely the fact that I used pre labeled data with the .csv file already provided but my images weren't in the same folder.
It is training now I think!
Could you tell me if stopping the training and restarting will resume where I left of or do I have to train it in one go?
Thanks for the help so far!

**Comment by AntonMu** [comment]
I assume, you will have to restart the training.
